### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by ACkuku** [sillybun/autoformatpythonstatement#1]
`File "ZYTFDUAUTOFORMATvimbufferutil.py", line 6
    self.adddict: Dict[int, List[str]] = dict()
                ^
SyntaxError: invalid syntax`

**Comment by sillybun** [comment]
A reason for this problem is that your vim support `python2` instead of `python3`.
You can run `echo has('python3')` to check for that.
you can put the following statement at the **top** of your `vimrc` to fix the problem:
```
if has('python3')
endif
```
